from geobr.utils import read_geobr_v2
from geobr._docstrings import docparams


@docparams
def read_urban_area(
    year: int,
    code_muni: str = "all",
    simplified: bool = False,
    output: str = "gpd",
    show_progress: bool = True,
    cache: bool = True,
    verbose: bool = False,
):
    """ Download spatial data of urbanized areas in Brazil (IBGE).

     This function reads the official data on the urban footprint of Brazilian cities.
     Orignal data were generated by Institute of Geography
    and Statistics (IBGE)  For more information about the methodology, see deails at
    https://biblioteca.ibge.gov.br/visualizacao/livros/liv100639.pdf

    Parameters
    ----------
    {year}
    {code_muni}
    {simplified}
    {output}
    {show_progress}
    {cache}
    {verbose}

    """

    return read_geobr_v2(
        "urbanareas",
        year,
        code=code_muni,
        simplified=simplified,
        output=output,
        show_progress=show_progress,
        cache=cache,
        verbose=verbose,
    )
