from geobr.utils import read_geobr_v2
from geobr._docstrings import docparams


@docparams
def read_municipal_seat(
    year: int,
    code_muni: str = "all",
    simplified: bool = False,
    output: str = "gpd",
    show_progress: bool = True,
    cache: bool = True,
    verbose: bool = False,
):
    """ Download spatial data of municipal seats (sede dos municipios) in Brazil (IBGE).

     This function reads the official data on the municipal seats (sede dos municipios) of Brazil.
 The data brings the spatial coordinates (lat lon) of of municipal seats for various years
 between 1872 and 2010. Orignal data were generated by Brazilian Institute of Geography
 and Statistics (IBGE).

    Parameters
    ----------
    {year}
    {code_muni}
    {simplified}
    {output}
    {show_progress}
    {cache}
    {verbose}

    """

    return read_geobr_v2(
        "municipalseats",
        year,
        code=code_muni,
        simplified=simplified,
        output=output,
        show_progress=show_progress,
        cache=cache,
        verbose=verbose,
    )
